export const TIMING_CONSTANTS = {
  OAM_SCAN_CYCLES: 80,
  DRAWING_CYCLES: 172,
  HBLANK_CYCLES: 204,
  SCANLINE_CYCLES: 456,
  VBLANK_LINES: 10,
  VISIBLE_LINES: 144,
  TOTAL_LINES: 154,
};

export const PPU_MODES = {
  HBLANK: 0,
  VBLANK: 1,
  OAM_SCAN: 2,
  DRAWING: 3,
};
